print("this is \\\\ double backsash")
print("these are  /\\/\\/\\/\\/\\ mountains")
print("he is \t\tawosome")
print("""\\" \\n \\t \\' """)
print("this is \\\ double backsash")
print("these are  /\/\/\/\/\ mountains")
print(r"this is \n double backsash")
print(2/2)
print(3//2)